spring:
  application:
    name: auth-service


  # =========================
  # DATABASE - LOCAL DEV (connects to Docker Postgres)
  # =========================
  datasource:
    url: jdbc:postgresql://localhost:5432/studyboard
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # =========================
  # JPA/HIBERNATE
  # =========================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        jdbc:
#          time_zone: Asia/Kolkata

# =========================
# JWT CONFIGURATION
# =========================
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

# =========================
# LOGGING
# =========================
logging:
  level:
    org.springframework.security: DEBUG
    com.studyboard: DEBUG

server:
  port: 8081